name: Assistente CI-CD Workflow

on:
  push:
    branches:
      - frontend-jo
  pull_request:
    branches:
      - frontend-jo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Building Docker Image for Frontend
        run: docker build -t aceleraprojetosfjs/assistentevirtual-frontend:latest ./frontend

      - name: Pushing Docker Image for Frontend
        run: docker push aceleraprojetosfjs/assistentevirtual-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker Image for Frontend
        run: docker pull aceleraprojetosfjs/assistentevirtual-frontend:latest

      - name: Stop and Remove Old Frontend Container
        run: docker rm -f frontend-container 

      - name: Deploy Docker Container for Frontend
        run: docker run -d --name frontend-container --env-file .env -p 3000:80 aceleraprojetosfjs/assistentevirtual-frontend:latest