name: Jo-Frontend CI-CD
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t  acelerafjsprojetos/frontendassistente .
      - name: Push Docker Image to DockerHub
        run: docker push acelerafjsprojetos/frontendassistente:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from DockerHub
        run: docker pull acelerafjsprojetos/frontendassistente:latest
      - name: Delect Old Container
        run: docker rm -f reactContainer
      - name: Run Docker Container
        run: docker run -d -p 3000:8000 --name reactContainer  acelerafjsprojetos/frontendassistente
