name: Build-Frontend.Js CI

on:
  push:
    branches: [ "08-jo-mvp" ]
  pull_request:
    branches: [ "08-jo-mvp"]

jobs:
  Build-Frontend:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies FRONTEND
        run: npm install && npm run build